# Generated by Django 5.1.1 on 2025-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='RAM',
            field=models.ManyToManyField(null=True, to='api.ram'),
        ),
        migrations.AddField(
            model_name='order',
            name='cases',
            field=models.ManyToManyField(null=True, to='api.case'),
        ),
        migrations.AddField(
            model_name='order',
            name='coolers',
            field=models.ManyToManyField(null=True, to='api.cooler'),
        ),
        migrations.AddField(
            model_name='order',
            name='discs',
            field=models.ManyToManyField(null=True, to='api.disc'),
        ),
        migrations.AddField(
            model_name='order',
            name='fan',
            field=models.ManyToManyField(null=True, to='api.fan'),
        ),
        migrations.AddField(
            model_name='order',
            name='graphic_cards',
            field=models.ManyToManyField(null=True, to='api.graphiccard'),
        ),
        migrations.AddField(
            model_name='order',
            name='headphones',
            field=models.ManyToManyField(null=True, to='api.headphones'),
        ),
        migrations.AddField(
            model_name='order',
            name='keyboard',
            field=models.ManyToManyField(null=True, to='api.keyboard'),
        ),
        migrations.AddField(
            model_name='order',
            name='monitor',
            field=models.ManyToManyField(null=True, to='api.monitor'),
        ),
        migrations.AddField(
            model_name='order',
            name='motherboards',
            field=models.ManyToManyField(null=True, to='api.motherboard'),
        ),
        migrations.AddField(
            model_name='order',
            name='mouse',
            field=models.ManyToManyField(null=True, to='api.mouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='power_unit',
            field=models.ManyToManyField(null=True, to='api.powerunit'),
        ),
        migrations.AddField(
            model_name='order',
            name='processors',
            field=models.ManyToManyField(null=True, to='api.processor'),
        ),
    ]
